// Generated by dts-bundle-generator v9.5.1

import { EventEmitter as EventEmitter$1 } from 'events';
import { EventEmitter as EventEmitter$2 } from 'stream';

export type Client = any;
export type ClientOptions = any;
export type Vec3 = any;
export type Item = any;
declare class Window<T = any> {
}
export type Recipe = any;
export type Block = any;
export type Entity = any;
export type ChatMessage = any;
declare namespace world {
	export type world = any;
	export type WorldSync = any;
}
export type Registry = any;
export type IndexedData = any;
export type EventEmitter = any;
export interface TypedEmitter<Events extends Record<string | symbol, any>> extends EventEmitter {
	on<E extends keyof Events>(event: E, listener: Events[E]): this;
	once<E extends keyof Events>(event: E, listener: Events[E]): this;
	emit<E extends keyof Events>(event: E, ...args: Parameters<Events[E] extends (...args: any[]) => any ? Events[E] : never>): boolean;
	removeAllListeners<E extends keyof Events>(event?: E): this;
}
export interface BotOptions extends ClientOptions {
	logErrors?: boolean;
	hideErrors?: boolean;
	loadInternalPlugins?: boolean;
	plugins?: PluginOptions;
	chat?: ChatLevel;
	colorsEnabled?: boolean;
	viewDistance?: ViewDistance;
	mainHand?: MainHands;
	difficulty?: number;
	chatLengthLimit?: number;
	physicsEnabled?: boolean;
	/** @default 4 */
	maxCatchupTicks?: number;
	client?: Client;
	brand?: string;
	defaultChatPatterns?: boolean;
	respawn?: boolean;
}
export type ChatLevel = "enabled" | "commandsOnly" | "disabled";
export type ViewDistance = "far" | "normal" | "short" | "tiny" | number;
export type MainHands = "left" | "right";
export interface PluginOptions {
	[plugin: string]: boolean | Plugin;
}
export type Plugin = (bot: Bot, options: BotOptions) => void;
export interface BotEvents {
	chat: (username: string, message: string, translate: string | null, jsonMsg: ChatMessage, matches: string[] | null) => Promise<void> | void;
	whisper: (username: string, message: string, translate: string | null, jsonMsg: ChatMessage, matches: string[] | null) => Promise<void> | void;
	actionBar: (jsonMsg: ChatMessage) => Promise<void> | void;
	error: (err: Error) => Promise<void> | void;
	message: (jsonMsg: ChatMessage, position: string) => Promise<void> | void;
	messagestr: (message: string, position: string, jsonMsg: ChatMessage) => Promise<void> | void;
	unmatchedMessage: (stringMsg: string, jsonMsg: ChatMessage) => Promise<void> | void;
	inject_allowed: () => Promise<void> | void;
	login: () => Promise<void> | void;
	/** When `respawn` option is disabled, you can call this method manually to respawn. */
	spawn: () => Promise<void> | void;
	respawn: () => Promise<void> | void;
	game: () => Promise<void> | void;
	title: (text: string, type: "subtitle" | "title") => Promise<void> | void;
	rain: () => Promise<void> | void;
	time: () => Promise<void> | void;
	kicked: (reason: string, loggedIn: boolean) => Promise<void> | void;
	end: (reason: string) => Promise<void> | void;
	spawnReset: () => Promise<void> | void;
	death: () => Promise<void> | void;
	health: () => Promise<void> | void;
	breath: () => Promise<void> | void;
	entitySwingArm: (entity: Entity) => Promise<void> | void;
	entityHurt: (entity: Entity, source: Entity) => Promise<void> | void;
	entityDead: (entity: Entity) => Promise<void> | void;
	entityTaming: (entity: Entity) => Promise<void> | void;
	entityTamed: (entity: Entity) => Promise<void> | void;
	entityShakingOffWater: (entity: Entity) => Promise<void> | void;
	entityEatingGrass: (entity: Entity) => Promise<void> | void;
	entityHandSwap: (entity: Entity) => Promise<void> | void;
	entityWake: (entity: Entity) => Promise<void> | void;
	entityEat: (entity: Entity) => Promise<void> | void;
	entityCriticalEffect: (entity: Entity) => Promise<void> | void;
	entityMagicCriticalEffect: (entity: Entity) => Promise<void> | void;
	entityCrouch: (entity: Entity) => Promise<void> | void;
	entityUncrouch: (entity: Entity) => Promise<void> | void;
	entityEquip: (entity: Entity) => Promise<void> | void;
	entitySleep: (entity: Entity) => Promise<void> | void;
	entitySpawn: (entity: Entity) => Promise<void> | void;
	entityElytraFlew: (entity: Entity) => Promise<void> | void;
	usedFirework: () => Promise<void> | void;
	itemDrop: (entity: Entity) => Promise<void> | void;
	playerCollect: (collector: Entity, collected: Entity) => Promise<void> | void;
	entityAttributes: (entity: Entity) => Promise<void> | void;
	entityGone: (entity: Entity) => Promise<void> | void;
	entityMoved: (entity: Entity) => Promise<void> | void;
	entityDetach: (entity: Entity, vehicle: Entity) => Promise<void> | void;
	entityAttach: (entity: Entity, vehicle: Entity) => Promise<void> | void;
	entityUpdate: (entity: Entity) => Promise<void> | void;
	entityEffect: (entity: Entity, effect: Effect) => Promise<void> | void;
	entityEffectEnd: (entity: Entity, effect: Effect) => Promise<void> | void;
	playerJoined: (player: Player) => Promise<void> | void;
	playerUpdated: (player: Player) => Promise<void> | void;
	playerLeft: (entity: Player) => Promise<void> | void;
	blockUpdate: (oldBlock: Block | null, newBlock: Block) => Promise<void> | void;
	"blockUpdate:(x, y, z)": (oldBlock: Block | null, newBlock: Block | null) => Promise<void> | void;
	chunkColumnLoad: (entity: Vec3) => Promise<void> | void;
	chunkColumnUnload: (entity: Vec3) => Promise<void> | void;
	soundEffectHeard: (soundName: string, position: Vec3, volume: number, pitch: number) => Promise<void> | void;
	hardcodedSoundEffectHeard: (soundId: number, soundCategory: number, position: Vec3, volume: number, pitch: number) => Promise<void> | void;
	noteHeard: (block: Block, instrument: Instrument, pitch: number) => Promise<void> | void;
	pistonMove: (block: Block, isPulling: number, direction: number) => Promise<void> | void;
	chestLidMove: (block: Block, isOpen: number, block2: Block | null) => Promise<void> | void;
	blockBreakProgressObserved: (block: Block, destroyStage: number) => Promise<void> | void;
	blockBreakProgressEnd: (block: Block) => Promise<void> | void;
	diggingCompleted: (block: Block) => Promise<void> | void;
	diggingAborted: (block: Block) => Promise<void> | void;
	move: (position: Vec3) => Promise<void> | void;
	forcedMove: () => Promise<void> | void;
	mount: () => Promise<void> | void;
	dismount: (vehicle: Entity) => Promise<void> | void;
	windowOpen: (window: Window) => Promise<void> | void;
	windowClose: (window: Window) => Promise<void> | void;
	sleep: () => Promise<void> | void;
	wake: () => Promise<void> | void;
	experience: () => Promise<void> | void;
	physicsTick: () => Promise<void> | void;
	physicTick: () => Promise<void> | void;
	scoreboardCreated: (scoreboard: ScoreBoard) => Promise<void> | void;
	scoreboardDeleted: (scoreboard: ScoreBoard) => Promise<void> | void;
	scoreboardTitleChanged: (scoreboard: ScoreBoard) => Promise<void> | void;
	scoreUpdated: (scoreboard: ScoreBoard, item: number) => Promise<void> | void;
	scoreRemoved: (scoreboard: ScoreBoard, item: number) => Promise<void> | void;
	scoreboardPosition: (position: DisplaySlot, scoreboard: ScoreBoard) => Promise<void> | void;
	teamCreated: (team: Team) => Promise<void> | void;
	teamRemoved: (team: Team) => Promise<void> | void;
	teamUpdated: (team: Team) => Promise<void> | void;
	teamMemberAdded: (team: Team) => Promise<void> | void;
	teamMemberRemoved: (team: Team) => Promise<void> | void;
	bossBarCreated: (bossBar: BossBar) => Promise<void> | void;
	bossBarDeleted: (bossBar: BossBar) => Promise<void> | void;
	bossBarUpdated: (bossBar: BossBar) => Promise<void> | void;
	resourcePack: (url: string, hash?: string, uuid?: string) => Promise<void> | void;
	heldItemChanged: (newItem: Item | null) => Promise<void> | void;
	particle: (particle: Particle) => Promise<void> | void;
}
export interface CommandBlockOptions {
	mode: number;
	trackOutput: boolean;
	conditional: boolean;
	alwaysActive: boolean;
}
interface Bot extends TypedEmitter<BotEvents> {
	username: string;
	protocolVersion: string;
	majorVersion: string;
	version: string;
	entity: Entity;
	entities: {
		[id: string]: Entity;
	};
	fireworkRocketDuration: number;
	spawnPoint: Vec3;
	game: GameState;
	player: Player;
	players: {
		[username: string]: Player;
	};
	isRaining: boolean;
	thunderState: number;
	chatPatterns: ChatPattern[];
	settings: GameSettings;
	experience: Experience;
	health: number;
	food: number;
	foodSaturation: number;
	oxygenLevel: number;
	physics: PhysicsOptions;
	physicsEnabled: boolean;
	time: Time;
	quickBarSlot: number;
	inventory: Window<StorageEvents>;
	targetDigBlock: Block;
	isSleeping: boolean;
	scoreboards: {
		[name: string]: ScoreBoard;
	};
	scoreboard: {
		[slot in DisplaySlot]: ScoreBoard;
	};
	teams: {
		[name: string]: Team;
	};
	teamMap: {
		[name: string]: Team;
	};
	controlState: ControlStateStatus;
	creative: creativeMethods;
	world: world.WorldSync;
	_client: Client;
	heldItem: Item | null;
	usingHeldItem: boolean;
	currentWindow: Window | null;
	simpleClick: simpleClick;
	tablist: Tablist;
	registry: Registry;
	connect: (options: BotOptions) => void;
	supportFeature: IndexedData["supportFeature"];
	end: (reason?: string) => void;
	blockAt: (point: Vec3, extraInfos?: boolean) => Block | null;
	blockInSight: (maxSteps: number, vectorLength: number) => Block | null;
	blockAtCursor: (maxDistance?: number, matcher?: Function) => Block | null;
	blockAtEntityCursor: (entity?: Entity, maxDistance?: number, matcher?: Function) => Block | null;
	canSeeBlock: (block: Block) => boolean;
	findBlock: (options: FindBlockOptions) => Block | null;
	findBlocks: (options: FindBlockOptions) => Vec3[];
	canDigBlock: (block: Block) => boolean;
	recipesFor: (itemType: number, metadata: number | null, minResultCount: number | null, craftingTable: Block | boolean | null) => Recipe[];
	recipesAll: (itemType: number, metadata: number | null, craftingTable: Block | boolean | null) => Recipe[];
	quit: (reason?: string) => void;
	tabComplete: (str: string, assumeCommand?: boolean, sendBlockInSight?: boolean, timeout?: number) => Promise<string[]>;
	chat: (message: string) => void;
	whisper: (username: string, message: string) => void;
	chatAddPattern: (pattern: RegExp, chatType: string, description?: string) => number;
	setSettings: (options: Partial<GameSettings>) => void;
	loadPlugin: (plugin: Plugin) => void;
	loadPlugins: (plugins: Plugin[]) => void;
	hasPlugin: (plugin: Plugin) => boolean;
	sleep: (bedBlock: Block) => Promise<void>;
	isABed: (bedBlock: Block) => boolean;
	wake: () => Promise<void>;
	elytraFly: () => Promise<void>;
	setControlState: (control: ControlState, state: boolean) => void;
	getControlState: (control: ControlState) => boolean;
	clearControlStates: () => void;
	getExplosionDamages: (targetEntity: Entity, position: Vec3, radius: number, rawDamages?: boolean) => number | null;
	lookAt: (point: Vec3, force?: boolean) => Promise<void>;
	look: (yaw: number, pitch: number, force?: boolean) => Promise<void>;
	updateSign: (block: Block, text: string, back?: boolean) => void;
	equip: (item: Item | number, destination: EquipmentDestination | null) => Promise<void>;
	unequip: (destination: EquipmentDestination | null) => Promise<void>;
	tossStack: (item: Item) => Promise<void>;
	toss: (itemType: number, metadata: number | null, count: number | null) => Promise<void>;
	dig: ((block: Block, forceLook?: boolean | "ignore") => Promise<void>) & ((block: Block, forceLook: boolean | "ignore", digFace: "auto" | Vec3 | "raycast") => Promise<void>);
	stopDigging: () => void;
	digTime: (block: Block) => number;
	placeBlock: (referenceBlock: Block, faceVector: Vec3) => Promise<void>;
	placeEntity: (referenceBlock: Block, faceVector: Vec3) => Promise<Entity>;
	activateBlock: (block: Block, direction?: Vec3, cursorPos?: Vec3) => Promise<void>;
	activateEntity: (entity: Entity) => Promise<void>;
	activateEntityAt: (entity: Entity, position: Vec3) => Promise<void>;
	consume: () => Promise<void>;
	fish: () => Promise<void>;
	activateItem: (offhand?: boolean) => void;
	deactivateItem: () => void;
	useOn: (targetEntity: Entity) => void;
	attack: (entity: Entity) => void;
	swingArm: (hand: "left" | "right" | undefined, showHand?: boolean) => void;
	mount: (entity: Entity) => void;
	dismount: () => void;
	moveVehicle: (left: number, forward: number) => void;
	setQuickBarSlot: (slot: number) => void;
	craft: (recipe: Recipe, count?: number, craftingTable?: Block) => Promise<void>;
	writeBook: (slot: number, pages: string[]) => Promise<void>;
	openContainer: (chest: Block | Entity, direction?: Vec3, cursorPos?: Vec3) => Promise<Chest | Dispenser>;
	openChest: (chest: Block | Entity, direction?: number, cursorPos?: Vec3) => Promise<Chest>;
	openFurnace: (furnace: Block) => Promise<Furnace>;
	openDispenser: (dispenser: Block) => Promise<Dispenser>;
	openEnchantmentTable: (enchantmentTable: Block) => Promise<EnchantmentTable>;
	openAnvil: (anvil: Block) => Promise<Anvil>;
	openVillager: (villager: Entity) => Promise<Villager>;
	trade: (villagerInstance: Villager, tradeIndex: string | number, times?: number) => Promise<void>;
	setCommandBlock: (pos: Vec3, command: string, options: CommandBlockOptions) => void;
	clickWindow: (slot: number, mouseButton: number, mode: number) => Promise<void>;
	putSelectedItemRange: (start: number, end: number, window: Window, slot: any) => Promise<void>;
	putAway: (slot: number) => Promise<void>;
	closeWindow: (window: Window) => void;
	transfer: (options: TransferOptions) => Promise<void>;
	openBlock: (block: Block, direction?: Vec3, cursorPos?: Vec3) => Promise<Window>;
	openEntity: (block: Entity, Class: new () => EventEmitter$1) => Promise<Window>;
	moveSlotItem: (sourceSlot: number, destSlot: number) => Promise<void>;
	updateHeldItem: () => void;
	getEquipmentDestSlot: (destination: string) => number;
	waitForChunksToLoad: () => Promise<void>;
	entityAtCursor: (maxDistance?: number) => Entity | null;
	nearestEntity: (filter?: (entity: Entity) => boolean) => Entity | null;
	waitForTicks: (ticks: number) => Promise<void>;
	addChatPattern: (name: string, pattern: RegExp, options?: chatPatternOptions) => number;
	addChatPatternSet: (name: string, patterns: RegExp[], options?: chatPatternOptions) => number;
	removeChatPattern: (name: string | number) => void;
	awaitMessage: (...args: string[] | RegExp[]) => Promise<string>;
	acceptResourcePack: () => void;
	denyResourcePack: () => void;
	respawn: () => void;
}
export interface simpleClick {
	leftMouse: (slot: number) => Promise<void>;
	rightMouse: (slot: number) => Promise<void>;
}
export interface Tablist {
	header: ChatMessage;
	footer: ChatMessage;
}
export interface chatPatternOptions {
	repeat: boolean;
	parse: boolean;
}
export interface GameState {
	levelType: LevelType;
	gameMode: GameMode;
	hardcore: boolean;
	dimension: Dimension;
	difficulty: Difficulty;
	maxPlayers: number;
	serverBrand: string;
}
export type LevelType = "default" | "flat" | "largeBiomes" | "amplified" | "customized" | "buffet" | "default_1_1";
export type GameMode = "survival" | "creative" | "adventure" | "spectator";
export type Dimension = "the_nether" | "overworld" | "the_end";
export type Difficulty = "peaceful" | "easy" | "normal" | "hard";
export interface Player {
	uuid: string;
	username: string;
	displayName: ChatMessage;
	gamemode: number;
	ping: number;
	entity: Entity;
	skinData: SkinData | undefined;
	profileKeys?: {
		publicKey: Buffer;
		signature: Buffer;
	};
}
export interface SkinData {
	url: string;
	model: string | null;
}
export interface ChatPattern {
	pattern: RegExp;
	type: string;
	description: string;
}
export interface SkinParts {
	showCape: boolean;
	showJacket: boolean;
	showLeftSleeve: boolean;
	showRightSleeve: boolean;
	showLeftPants: boolean;
	showRightPants: boolean;
	showHat: boolean;
}
export interface GameSettings {
	chat: ChatLevel;
	colorsEnabled: boolean;
	viewDistance: ViewDistance;
	difficulty: number;
	skinParts: SkinParts;
	mainHand: MainHands;
}
export interface Experience {
	level: number;
	points: number;
	progress: number;
}
export interface PhysicsOptions {
	maxGroundSpeed: number;
	terminalVelocity: number;
	walkingAcceleration: number;
	gravity: number;
	groundFriction: number;
	playerApothem: number;
	playerHeight: number;
	jumpSpeed: number;
	yawSpeed: number;
	pitchSpeed: number;
	sprintSpeed: number;
	maxGroundSpeedSoulSand: number;
	maxGroundSpeedWater: number;
}
export interface Time {
	doDaylightCycle: boolean;
	bigTime: BigInt;
	time: number;
	timeOfDay: number;
	day: number;
	isDay: boolean;
	moonPhase: number;
	bigAge: BigInt;
	age: number;
}
export interface ControlStateStatus {
	forward: boolean;
	back: boolean;
	left: boolean;
	right: boolean;
	jump: boolean;
	sprint: boolean;
	sneak: boolean;
}
export type ControlState = "forward" | "back" | "left" | "right" | "jump" | "sprint" | "sneak";
export interface Effect {
	id: number;
	amplifier: number;
	duration: number;
}
export interface Instrument {
	id: number;
	name: "harp" | "doubleBass" | "snareDrum" | "sticks" | "bassDrum";
}
export interface FindBlockOptions {
	point?: Vec3;
	matching: number | number[] | ((block: Block) => boolean);
	maxDistance?: number;
	count?: number;
	useExtraInfo?: boolean | ((block: Block) => boolean);
}
export type EquipmentDestination = "hand" | "head" | "torso" | "legs" | "feet" | "off-hand";
export interface TransferOptions {
	window: Window;
	itemType: number;
	metadata: number | null;
	count?: number;
	sourceStart: number;
	sourceEnd: number;
	destStart: number;
	destEnd: number;
}
export interface creativeMethods {
	setInventorySlot: (slot: number, item: Item | null) => Promise<void>;
	clearSlot: (slot: number) => Promise<void>;
	clearInventory: () => Promise<void>;
	flyTo: (destination: Vec3) => Promise<void>;
	startFlying: () => void;
	stopFlying: () => void;
}
export interface StorageEvents {
	open: () => void;
	close: () => void;
	updateSlot: (slot: number, oldItem: Item | null, newItem: Item | null) => void;
}
export interface FurnaceEvents extends StorageEvents {
	update: () => void;
}
export interface ConditionalStorageEvents extends StorageEvents {
	ready: () => void;
}
declare class Chest extends Window<StorageEvents> {
	constructor();
	close(): void;
	deposit(itemType: number, metadata: number | null, count: number | null): Promise<void>;
	withdraw(itemType: number, metadata: number | null, count: number | null): Promise<void>;
}
declare class Furnace extends Window<FurnaceEvents> {
	fuel: number;
	progress: number;
	constructor();
	close(): void;
	takeInput(): Promise<Item>;
	takeFuel(): Promise<Item>;
	takeOutput(): Promise<Item>;
	putInput(itemType: number, metadata: number | null, count: number): Promise<void>;
	putFuel(itemType: number, metadata: number | null, count: number): Promise<void>;
	inputItem(): Item;
	fuelItem(): Item;
	outputItem(): Item;
}
declare class Dispenser extends Window<StorageEvents> {
	constructor();
	close(): void;
	deposit(itemType: number, metadata: number | null, count: number | null): Promise<void>;
	withdraw(itemType: number, metadata: number | null, count: number | null): Promise<void>;
}
declare class EnchantmentTable extends Window<ConditionalStorageEvents> {
	enchantments: Enchantment[];
	constructor();
	close(): void;
	targetItem(): Item;
	enchant(choice: string | number): Promise<Item>;
	takeTargetItem(): Promise<Item>;
	putTargetItem(item: Item): Promise<Item>;
	putLapis(item: Item): Promise<Item>;
}
declare class Anvil {
	combine(itemOne: Item, itemTwo: Item, name?: string): Promise<void>;
	rename(item: Item, name?: string): Promise<void>;
}
export interface Enchantment {
	level: number;
	expected: {
		enchant: number;
		level: number;
	};
}
declare class Villager extends Window<ConditionalStorageEvents> {
	trades: VillagerTrade[];
	constructor();
	close(): void;
}
export interface VillagerTrade {
	inputItem1: Item;
	outputItem: Item;
	inputItem2: Item | null;
	hasItem2: boolean;
	tradeDisabled: boolean;
	nbTradeUses: number;
	maximumNbTradeUses: number;
	xp?: number;
	specialPrice?: number;
	priceMultiplier?: number;
	demand?: number;
	realPrice?: number;
}
declare class ScoreBoard {
	name: string;
	title: string;
	itemsMap: {
		[name: string]: ScoreBoardItem;
	};
	items: ScoreBoardItem[];
	constructor(packet: object);
	setTitle(title: string): void;
	add(name: string, value: number): ScoreBoardItem;
	remove(name: string): ScoreBoardItem;
}
export interface ScoreBoardItem {
	name: string;
	displayName: ChatMessage;
	value: number;
}
declare class Team {
	team: string;
	name: ChatMessage;
	friendlyFire: number;
	nameTagVisibility: string;
	collisionRule: string;
	color: string;
	prefix: ChatMessage;
	suffix: ChatMessage;
	memberMap: {
		[name: string]: "";
	};
	members: string[];
	constructor(team: string, name: string, friendlyFire: boolean, nameTagVisibility: string, collisionRule: string, formatting: number, prefix: string, suffix: string);
	parseMessage(value: string): ChatMessage;
	add(name: string, value: number): void;
	remove(name: string): void;
	update(name: string, friendlyFire: boolean, nameTagVisibility: string, collisionRule: string, formatting: number, prefix: string, suffix: string): void;
	displayName(member: string): ChatMessage;
}
export type DisplaySlot = "list" | "sidebar" | "belowName" | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18;
declare class BossBar {
	entityUUID: string;
	title: ChatMessage;
	health: number;
	dividers: number;
	color: "pink" | "blue" | "red" | "green" | "yellow" | "purple" | "white";
	shouldDarkenSky: boolean;
	isDragonBar: boolean;
	createFog: boolean;
	shouldCreateFog: boolean;
	constructor(uuid: string, title: string, health: number, dividers: number, color: number, flags: number);
}
declare class Particle {
	id: number;
	position: Vec3;
	offset: Vec3;
	count: number;
	movementSpeed: number;
	longDistanceRender: boolean;
	static fromNetwork(packet: Object): Particle;
	constructor(id: number, position: Vec3, offset: Vec3, count?: number, movementSpeed?: number, longDistanceRender?: boolean);
}
declare class ModuleManifest {
	constructor(data: IModuleManifest);
	getName(): string;
	getMain(): string;
	getDescription(): string;
	getVersion(): string;
	getDependencies(): string[];
	getSoftDependencies(): string[];
	getLoadBefore(): string[];
	getPermissions(): string[];
	getApiVersion(): string | undefined;
	getAuthor(): string | string[] | undefined;
	getWebsite(): string | undefined;
	getLoadPhase(): "STARTUP" | "LOGIN" | "SPAWN" | undefined;
	getCommands(): Record<string, any> | undefined;
}
declare class ModuleManager {
	dir: string;
	constructor(client: Client$1);
	loadModules(dir: string, targetFile?: string): void;
	getModules(): Map<string, XadyModule>;
	reloadModule(name: string): boolean;
	private watchLibsFolder;
	private extractTypesFromXext;
	private updateTsConfigPaths;
}
export declare class CommandSender {
	constructor(client: Client$1, name: string);
	getName(): string;
	sendMessage(message: string): void;
	hasPermission(permission: string): boolean;
}
export interface CommandExecutor {
	onCommand(sender: CommandSender, command: PluginCommand, label: string, args: string[]): boolean | Promise<boolean>;
}
export interface TabCompleter {
	onTabComplete(sender: CommandSender, command: PluginCommand, label: string, args: string[]): string[] | Promise<string[]>;
}
export declare class PluginCommand {
	private name;
	private description;
	private usageMessage;
	private permission;
	private permissionMessage;
	private aliases;
	private module;
	private executor;
	private tabCompleter;
	constructor(name: string, module?: XadyModule | null);
	getName(): string;
	getModule(): XadyModule | null;
	getDescription(): string;
	setDescription(description: string): this;
	getUsage(): string;
	setUsage(usage: string): this;
	getPermission(): string | null;
	setPermission(permission: string | null): this;
	getPermissionMessage(): string;
	setPermissionMessage(permissionMessage: string): this;
	getAliases(): string[];
	setAliases(aliases: string[]): this;
	setExecutor(executor: CommandExecutor): this;
	getExecutor(): CommandExecutor | null;
	setTabCompleter(tabCompleter: TabCompleter): this;
	getTabCompleter(): TabCompleter | null;
	execute(sender: CommandSender, label: string, args: string[]): Promise<boolean>;
	tabComplete(sender: CommandSender, label: string, args: string[]): Promise<string[]>;
}
declare class CommandManager {
	private commands;
	private client;
	constructor(client: Client$1);
	loadCommands: (dir: string) => unknown[];
	registerCommand(command: PluginCommand): void;
	getCommand(name: string): PluginCommand | undefined;
	getCommands(): Map<string, PluginCommand[]>;
	unregisterAll(module: XadyModule): void;
	executeCommand(sender: CommandSender, rawCommand: string): Promise<void>;
}
export declare class ConsoleCommandSender extends CommandSender {
	sendMessage(message: string): void;
	hasPermission(permission: string): boolean;
}
export interface Listener {
}
export declare abstract class XadyEvent {
	private eventName;
	constructor();
	getEventName(): string;
}
declare class EventManager {
	private handlers;
	private moduleListeners;
	private metadataCache;
	private chatPatternHandlers;
	eventMetrics: Map<string, {
		count: number;
		totalDurationMs: number;
	}>;
	registerEvents(listener: Listener, module: XadyModule | null): void;
	private rebuildChatPatternHandlersCache;
	unregisterAll(module: XadyModule): void;
	callEvent(event: XadyEvent): XadyEvent;
}
/**
 * Service Priority - Hangi servis sağlayıcısının öncelikli olduğunu belirler
 */
export declare enum ServicePriority {
	LOWEST = 5,
	LOW = 4,
	NORMAL = 3,
	HIGH = 2,
	HIGHEST = 1
}
declare class ServiceManager {
	private services;
	private moduleServices;
	/**
	 * Bir servisi register eder
	 *
	 * @param serviceClass Servis interface/class'ı
	 * @param service Servis implementasyonu
	 * @param provider Servisi sağlayan modül
	 * @param priority Servis önceliği (varsayılan: NORMAL)
	 */
	register<T>(serviceClass: new (...args: unknown[]) => T, service: T, provider: XadyModule, priority?: ServicePriority): void;
	/**
	 * Bir servisi unregister eder
	 *
	 * @param serviceClass Servis class'ı
	 * @param provider Servisi sağlayan modül
	 */
	unregister<T>(serviceClass: new (...args: unknown[]) => T, provider: XadyModule): void;
	/**
	 * Bir modülün tüm servislerini unregister eder
	 *
	 * @param provider Modül
	 */
	unregisterAll(provider: XadyModule): void;
	/**
	 * En yüksek öncelikli servisi döndürür
	 *
	 * @param serviceClass Servis class'ı
	 * @returns Servis veya undefined
	 */
	getService<T>(serviceClass: new (...args: unknown[]) => T): T | undefined;
	/**
	 * Belirli bir önceliğe sahip servisi döndürür
	 *
	 * @param serviceClass Servis class'ı
	 * @param priority Öncelik
	 * @returns Servis veya undefined
	 */
	getServiceByPriority<T>(serviceClass: new (...args: unknown[]) => T, priority: ServicePriority): T | undefined;
	/**
	 * Tüm servisleri döndürür (öncelik sırasına göre)
	 *
	 * @param serviceClass Servis class'ı
	 * @returns Servis listesi
	 */
	getServices<T>(serviceClass: new (...args: unknown[]) => T): T[];
	/**
	 * Servis kayıtlı mı kontrol eder
	 *
	 * @param serviceClass Servis class'ı
	 * @returns Kayıtlı mı
	 */
	isServiceRegistered<T>(serviceClass: new (...args: unknown[]) => T): boolean;
	/**
	 * Belirli bir modülün servisi sağlayıp sağlamadığını kontrol eder
	 *
	 * @param serviceClass Servis class'ı
	 * @param provider Modül
	 * @returns Sağlıyor mu
	 */
	isProvidedBy<T>(serviceClass: new (...args: unknown[]) => T, provider: XadyModule): boolean;
	/**
	 * Bir servisin sağlayıcısını döndürür
	 *
	 * @param serviceClass Servis class'ı
	 * @returns Sağlayıcı modül veya undefined
	 */
	getProvider<T>(serviceClass: new (...args: unknown[]) => T): XadyModule | undefined;
	/**
	 * Tüm kayıtlı servisleri listeler
	 */
	listServices(): void;
}
declare class Client$1 extends EventEmitter$2 {
	private bot?;
	private safeBot?;
	private botOptions?;
	private reconnectAttempts;
	private reconnectTimeout?;
	private patternOwners;
	constructor(execDir: string);
	startBot(options: BotOptions): void;
	private handleReconnect;
	getModuleManager(): ModuleManager;
	getCommandManager(): CommandManager;
	getEventManager(): EventManager;
	getServiceManager(): ServiceManager;
	getExecDir(): string;
	registerPatternOwner(name: string, module: XadyModule): void;
	unregisterPatternOwner(name: string): void;
	getPatternOwner(name: string): XadyModule | undefined;
	getBot(): Bot$1 | undefined;
	getConsoleCommandSender(): ConsoleCommandSender;
	getBotOptions(): BotOptions | undefined;
	on<K extends keyof Events>(eventName: K, listener: (...args: Parameters<Events[K]>) => void): this;
}
export declare class FileConfiguration {
	private file;
	private data;
	constructor(file: string);
	load(): void;
	save(): void;
	private getPath;
	get(pathStr: string, def?: any): any;
	getString(pathStr: string, def?: string): string;
	getInt(pathStr: string, def?: number): number;
	getNumber(pathStr: string, def?: number): number;
	getBoolean(pathStr: string, def?: boolean): boolean;
	getList(pathStr: string, def?: any[]): any[];
	getStringList(pathStr: string): string[];
	set(pathStr: string, value: any): void;
	contains(pathStr: string): boolean;
	getKeys(deep?: boolean): string[];
}
export declare abstract class XadyModule extends EventEmitter$1 {
	protected manifest: ModuleManifest;
	protected client: Client$1;
	protected execDir: string;
	protected dataFolder: string;
	protected xextPath: string;
	private _config;
	private commands;
	private chatPatterns;
	private trackedTimeouts;
	private trackedIntervals;
	private _exports;
	abstract onEnable(): void;
	abstract onDisable(): void;
	constructor(client: Client$1);
	onLoad(): void;
	setEnabled(enabled: boolean): void;
	getServer(): Bot$1 | undefined;
	getBot(): Bot$1 | undefined;
	getClient(): Client$1;
	setTimeout(callback: (...args: unknown[]) => void, ms?: number, ...args: unknown[]): NodeJS.Timeout;
	clearTimeout(timeoutId: NodeJS.Timeout): void;
	setInterval(callback: (...args: unknown[]) => void, ms?: number, ...args: unknown[]): NodeJS.Timeout;
	clearInterval(intervalId: NodeJS.Timeout): void;
	private clearAllTrackedTimers;
	runTask(callback: () => void | Promise<void>): number;
	runTaskLater(callback: () => void | Promise<void>, delayTicks: number): number;
	runTaskTimer(callback: () => void | Promise<void>, delayTicks: number, intervalTicks: number): number;
	runTaskAsync(callback: () => void | Promise<void>): number;
	runTaskLaterAsync(callback: () => void | Promise<void>, delayTicks: number): number;
	runTaskTimerAsync(callback: () => void | Promise<void>, delayTicks: number, intervalTicks: number): number;
	cancelTask(taskId: number): boolean;
	protected static getModule<T extends XadyModule>(prototype: string): T;
	protected static getModule<T extends XadyModule>(prototype: (new () => T)): T;
	isEnabled(): boolean;
	getEnabled(): boolean;
	getModuleManifest(): ModuleManifest;
	getExecDir(): string;
	getDescription(): ModuleManifest;
	getName(): string;
	getDataFolder(): string;
	getCommand(name: string): PluginCommand | null;
	_setCommand(name: string, command: PluginCommand): void;
	getResource(filename: string): Buffer | null;
	saveResource(resourcePath: string, replace?: boolean): void;
	saveDefaultConfig(): void;
	getConfig(): FileConfiguration;
	reloadConfig(): void;
	saveConfig(): void;
	registerEvents(listener: Listener): void;
	callEvent(event: XadyEvent): XadyEvent;
	registerChatPattern(name: string, pattern: RegExp): void;
	unregisterChatPattern(name: string): void;
	unregisterAllChatPatterns(): void;
	registerService<T>(serviceClass: new (...args: unknown[]) => T, service: T, priority?: number): void;
	unregisterService<T>(serviceClass: new (...args: unknown[]) => T): void;
	getService<T>(serviceClass: new (...args: unknown[]) => T): T | undefined;
	isServiceAvailable<T>(serviceClass: new (...args: unknown[]) => T): boolean;
	getLogger(): {
		info: (msg: string) => void;
		warn: (msg: string) => void;
		error: (msg: string) => void;
		severe: (msg: string) => void;
		fine: (msg: string) => void;
		finest: (msg: string) => void;
	};
	export(name: string, value: any): any;
	getExport(name: string): any;
	invoke(methodName: string, ...args: any[]): any;
}
declare class Response$1 {
	success: boolean;
	message: string;
	constructor(success: boolean, message: string);
	toJson(): {
		success: boolean;
		message: string;
	};
	toString(): string;
	valueOf(): {
		success: boolean;
		message: string;
	};
}
export declare const xady: string;
export declare const error: string;
export declare const success: string;
declare const module$1: string;
export declare const command: string;
export declare const event: string;
export declare abstract class Command {
	constructor(name: string);
	getName(): string;
	abstract execute(bot: Bot$1, sender: CommandSender, args: string[]): void | Promise<void>;
}
export declare enum EventPriority {
	LOWEST = 0,
	LOW = 1,
	NORMAL = 2,
	HIGH = 3,
	HIGHEST = 4,
	MONITOR = 5
}
export declare function EventHandler(priority?: EventPriority): any;
export interface Cancellable {
	isCancelled(): boolean;
	setCancelled(cancel: boolean): void;
}
declare class PlayerChatEvent extends XadyEvent implements Cancellable {
	private username;
	private message;
	private cancelled;
	constructor(username: string, message: string);
	getUsername(): string;
	getMessage(): string;
	setMessage(message: string): void;
	isCancelled(): boolean;
	setCancelled(cancel: boolean): void;
}
declare class MessageEvent$1 extends XadyEvent {
	private jsonMsg;
	private position;
	constructor(jsonMsg: ChatMessage, position: string);
	/**
	 * Mesajın JSON formatını döndürür
	 */
	getJsonMessage(): ChatMessage;
	/**
	 * Mesajın pozisyonunu döndürür (chat, system, game_info vb.)
	 */
	getPosition(): string;
	/**
	 * Mesajı düz metin olarak döndürür
	 */
	toString(): string;
	/**
	 * Mesajı ANSI renkleriyle döndürür
	 */
	toAnsi(): string;
	/**
	 * Mesajı renkler olmadan döndürür
	 */
	toMotd(): string;
}
declare class PlayerJoinEvent extends XadyEvent {
	private player;
	constructor(player: Player);
	getPlayer(): Player;
	getUsername(): string;
	getUUID(): string;
}
declare class PlayerLeftEvent extends XadyEvent {
	private player;
	constructor(player: Player);
	getPlayer(): Player;
	getUsername(): string;
	getUUID(): string;
}
declare class SpawnEvent extends XadyEvent {
	constructor();
}
declare class DeathEvent extends XadyEvent {
	constructor();
}
declare class HealthEvent extends XadyEvent {
	constructor();
}
declare class KickedEvent extends XadyEvent {
	private reason;
	private loggedIn;
	constructor(reason: string, loggedIn: boolean);
	getReason(): string;
	isLoggedIn(): boolean;
}
declare class EndEvent extends XadyEvent {
	private reason;
	constructor(reason: string);
	getReason(): string;
}
declare class ErrorEvent$1 extends XadyEvent {
	private error;
	constructor(error: Error);
	getError(): Error;
	getMessage(): string;
	getStack(): string | undefined;
}
declare class WhisperEvent extends XadyEvent implements Cancellable {
	private username;
	private message;
	private translate;
	private cancelled;
	constructor(username: string, message: string, translate: string | null);
	getUsername(): string;
	getMessage(): string;
	getTranslate(): string | null;
	isCancelled(): boolean;
	setCancelled(cancel: boolean): void;
}
declare class EntitySpawnEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
	getEntityId(): number;
	getEntityType(): string;
	getEntityName(): string | null;
	getPosition(): {
		x: number;
		y: number;
		z: number;
	};
}
declare class EntityGoneEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
	getEntityId(): number;
	getEntityType(): string;
}
declare class GenericMineflayerEvent extends XadyEvent {
	private originalEventName;
	private args;
	constructor(eventName: string, args: unknown[]);
	getOriginalEventName(): string;
	getArgs(): unknown[];
}
declare class ClientChatTypeEvent extends XadyEvent implements Cancellable {
	private cancelled;
	private text;
	constructor(text: string);
	setCancelled(cancel: boolean): void;
	isCancelled(): boolean;
	getText(): string;
}
declare class ActionBarEvent extends XadyEvent {
	private jsonMsg;
	constructor(jsonMsg: ChatMessage);
	getJsonMsg(): ChatMessage;
}
declare class MessageStrEvent extends XadyEvent {
	private message;
	private position;
	private jsonMsg;
	constructor(message: string, position: string, jsonMsg: ChatMessage);
	getMessage(): string;
	getPosition(): string;
	getJsonMsg(): ChatMessage;
}
declare class UnmatchedMessageEvent extends XadyEvent {
	private stringMsg;
	private jsonMsg;
	constructor(stringMsg: string, jsonMsg: ChatMessage);
	getStringMsg(): string;
	getJsonMsg(): ChatMessage;
}
declare class InjectAllowedEvent extends XadyEvent {
	constructor();
}
declare class LoginEvent extends XadyEvent {
	constructor();
}
declare class RespawnEvent extends XadyEvent {
	constructor();
}
declare class GameEvent extends XadyEvent {
	constructor();
}
declare class TitleEvent extends XadyEvent {
	private text;
	private type;
	constructor(text: string, type: string);
	getText(): string;
	getType(): string;
}
declare class RainEvent extends XadyEvent {
	constructor();
}
declare class TimeEvent extends XadyEvent {
	constructor();
}
declare class SpawnResetEvent extends XadyEvent {
	constructor();
}
declare class BreathEvent extends XadyEvent {
	constructor();
}
declare class MoveEvent extends XadyEvent {
	private position;
	constructor(position: Vec3);
	getPosition(): Vec3;
}
declare class ForcedMoveEvent extends XadyEvent {
	constructor();
}
declare class MountEvent extends XadyEvent {
	constructor();
}
declare class DismountEvent extends XadyEvent {
	private vehicle;
	constructor(vehicle: Entity);
	getVehicle(): Entity;
}
declare class SleepEvent extends XadyEvent {
	constructor();
}
declare class WakeEvent extends XadyEvent {
	constructor();
}
declare class ExperienceEvent extends XadyEvent {
	constructor();
}
declare class UsedFireworkEvent extends XadyEvent {
	constructor();
}
declare class EntitySwingArmEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityHurtEvent extends XadyEvent {
	private entity;
	private source;
	constructor(entity: Entity, source: Entity);
	getEntity(): Entity;
	getSource(): Entity;
}
declare class EntityDeadEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityTamingEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityTamedEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityShakingOffWaterEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityEatingGrassEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityHandSwapEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityWakeEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityEatEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityCriticalEffectEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityMagicCriticalEffectEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityCrouchEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityUncrouchEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityEquipEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntitySleepEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityElytraFlewEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class ItemDropEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class PlayerCollectEvent extends XadyEvent {
	private collector;
	private collected;
	constructor(collector: Entity, collected: Entity);
	getCollector(): Entity;
	getCollected(): Entity;
}
declare class EntityAttributesEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityMovedEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityDetachEvent extends XadyEvent {
	private entity;
	private vehicle;
	constructor(entity: Entity, vehicle: Entity);
	getEntity(): Entity;
	getVehicle(): Entity;
}
declare class EntityAttachEvent extends XadyEvent {
	private entity;
	private vehicle;
	constructor(entity: Entity, vehicle: Entity);
	getEntity(): Entity;
	getVehicle(): Entity;
}
declare class EntityUpdateEvent extends XadyEvent {
	private entity;
	constructor(entity: Entity);
	getEntity(): Entity;
}
declare class EntityEffectEvent extends XadyEvent {
	private entity;
	private effect;
	constructor(entity: Entity, effect: Effect);
	getEntity(): Entity;
	getEffect(): Effect;
}
declare class EntityEffectEndEvent extends XadyEvent {
	private entity;
	private effect;
	constructor(entity: Entity, effect: Effect);
	getEntity(): Entity;
	getEffect(): Effect;
}
declare class PlayerUpdatedEvent extends XadyEvent {
	private player;
	constructor(player: Player);
	getPlayer(): Player;
}
declare class BlockUpdateEvent extends XadyEvent {
	private oldBlock;
	private newBlock;
	constructor(oldBlock: Block | null, newBlock: Block);
	getOldBlock(): Block | null;
	getNewBlock(): Block;
}
declare class ChunkColumnLoadEvent extends XadyEvent {
	private point;
	constructor(point: Vec3);
	getPoint(): Vec3;
}
declare class ChunkColumnUnloadEvent extends XadyEvent {
	private point;
	constructor(point: Vec3);
	getPoint(): Vec3;
}
declare class SoundEffectHeardEvent extends XadyEvent {
	private soundName;
	private position;
	private volume;
	private pitch;
	constructor(soundName: string, position: Vec3, volume: number, pitch: number);
	getSoundName(): string;
	getPosition(): Vec3;
	getVolume(): number;
	getPitch(): number;
}
declare class HardcodedSoundEffectHeardEvent extends XadyEvent {
	private soundId;
	private soundCategory;
	private position;
	private volume;
	private pitch;
	constructor(soundId: number, soundCategory: number, position: Vec3, volume: number, pitch: number);
	getSoundId(): number;
	getSoundCategory(): number;
	getPosition(): Vec3;
	getVolume(): number;
	getPitch(): number;
}
declare class NoteHeardEvent extends XadyEvent {
	private block;
	private instrument;
	private pitch;
	constructor(block: Block, instrument: Instrument, pitch: number);
	getBlock(): Block;
	getInstrument(): Instrument;
	getPitch(): number;
}
declare class PistonMoveEvent extends XadyEvent {
	private block;
	private isPulling;
	private direction;
	constructor(block: Block, isPulling: number, direction: number);
	getBlock(): Block;
	getIsPulling(): number;
	getDirection(): number;
}
declare class ChestLidMoveEvent extends XadyEvent {
	private block;
	private isOpen;
	private block2;
	constructor(block: Block, isOpen: number, block2: Block | null);
	getBlock(): Block;
	getIsOpen(): number;
	getBlock2(): Block | null;
}
declare class BlockBreakProgressObservedEvent extends XadyEvent {
	private block;
	private destroyStage;
	constructor(block: Block, destroyStage: number);
	getBlock(): Block;
	getDestroyStage(): number;
}
declare class BlockBreakProgressEndEvent extends XadyEvent {
	private block;
	constructor(block: Block);
	getBlock(): Block;
}
declare class DiggingCompletedEvent extends XadyEvent {
	private block;
	constructor(block: Block);
	getBlock(): Block;
}
declare class DiggingAbortedEvent extends XadyEvent {
	private block;
	constructor(block: Block);
	getBlock(): Block;
}
declare class WindowOpenEvent extends XadyEvent {
	private window;
	constructor(window: Window);
	getWindow(): Window;
}
declare class WindowCloseEvent extends XadyEvent {
	private window;
	constructor(window: Window);
	getWindow(): Window;
}
declare class PhysicsTickEvent extends XadyEvent {
	constructor();
}
declare class ScoreboardCreatedEvent extends XadyEvent {
	private scoreboard;
	constructor(scoreboard: ScoreBoard);
	getScoreboard(): ScoreBoard;
}
declare class ScoreboardDeletedEvent extends XadyEvent {
	private scoreboard;
	constructor(scoreboard: ScoreBoard);
	getScoreboard(): ScoreBoard;
}
declare class ScoreboardTitleChangedEvent extends XadyEvent {
	private scoreboard;
	constructor(scoreboard: ScoreBoard);
	getScoreboard(): ScoreBoard;
}
declare class ScoreUpdatedEvent extends XadyEvent {
	private scoreboard;
	private item;
	constructor(scoreboard: ScoreBoard, item: number);
	getScoreboard(): ScoreBoard;
	getItem(): number;
}
declare class ScoreRemovedEvent extends XadyEvent {
	private scoreboard;
	private item;
	constructor(scoreboard: ScoreBoard, item: number);
	getScoreboard(): ScoreBoard;
	getItem(): number;
}
declare class ScoreboardPositionEvent extends XadyEvent {
	private position;
	private scoreboard;
	constructor(position: DisplaySlot, scoreboard: ScoreBoard);
	getPosition(): DisplaySlot;
	getScoreboard(): ScoreBoard;
}
declare class TeamCreatedEvent extends XadyEvent {
	private team;
	constructor(team: Team);
	getTeam(): Team;
}
declare class TeamRemovedEvent extends XadyEvent {
	private team;
	constructor(team: Team);
	getTeam(): Team;
}
declare class TeamUpdatedEvent extends XadyEvent {
	private team;
	constructor(team: Team);
	getTeam(): Team;
}
declare class TeamMemberAddedEvent extends XadyEvent {
	private team;
	constructor(team: Team);
	getTeam(): Team;
}
declare class TeamMemberRemovedEvent extends XadyEvent {
	private team;
	constructor(team: Team);
	getTeam(): Team;
}
declare class BossBarCreatedEvent extends XadyEvent {
	private bossBar;
	constructor(bossBar: BossBar);
	getBossBar(): BossBar;
}
declare class BossBarDeletedEvent extends XadyEvent {
	private bossBar;
	constructor(bossBar: BossBar);
	getBossBar(): BossBar;
}
declare class BossBarUpdatedEvent extends XadyEvent {
	private bossBar;
	constructor(bossBar: BossBar);
	getBossBar(): BossBar;
}
declare class ResourcePackEvent extends XadyEvent {
	private url;
	private hash;
	private uuid;
	constructor(url: string, hash: string, uuid: string);
	getUrl(): string;
	getHash(): string;
	getUuid(): string;
}
declare class ParticleEvent extends XadyEvent {
	private particle;
	constructor(particle: Particle);
	getParticle(): Particle;
}
export declare class ConsoleCommandEvent extends XadyEvent implements Cancellable {
	private cancelled;
	private command;
	private args;
	private label;
	constructor(command: string, args: string[]);
	getCommand(): string;
	getLabel(): string;
	getArgs(): string[];
	isCancelled(): boolean;
	setCancelled(cancelled: boolean): void;
}
export declare class ConsoleChatEvent extends XadyEvent implements Cancellable {
	private cancelled;
	private message;
	constructor(message: string);
	getMessage(): string;
	setMessage(message: string): void;
	isCancelled(): boolean;
	setCancelled(cancelled: boolean): void;
}
export declare class ChatPatternEvent extends XadyEvent {
	private patternName;
	private matches;
	private ownerModule?;
	constructor(patternName: string, matches: RegExpMatchArray, ownerModule?: XadyModule);
	getPatternName(): string;
	getMatches(): RegExpMatchArray;
	getMatch(index: number): string | undefined;
	getFullMatch(): string;
	getOwnerModule(): XadyModule | undefined;
	/**
	 * Named Capture Group: İsimlendirilmiş yakalama grubunun değerini döndürür.
	 * Regex'te `(?<name>...)` ile tanımlanan grupları alabilirsiniz.
	 *
	 * @example
	 * // Pattern: /(?<player>\w+) joined/
	 * event.getParam("player") // => "Steve"
	 */
	getParam(name: string): string | undefined;
	/**
	 * Tüm named capture group'ları bir obje olarak döndürür.
	 *
	 * @example
	 * // Pattern: /(?<player>\w+) gave (?<amount>\d+) diamonds to (?<target>\w+)/
	 * event.getParams() // => { player: "Steve", amount: "64", target: "Alex" }
	 */
	getParams(): Record<string, string> | undefined;
}
export declare enum TaskPriority {
	HIGH = 2,
	NORMAL = 1,
	LOW = 0
}
export declare class WorkerPool {
	private static instance;
	private workers;
	private activeWorkers;
	private taskQueue;
	private activeTasks;
	private maxWorkers;
	private cpuAffinity;
	private nextTaskId;
	private isEnabled;
	private constructor();
	static getInstance(): WorkerPool;
	init(enabled: boolean, maxWorkers: number, cpuAffinity: string): void;
	execute<T>(fn: (...args: any[]) => T | Promise<T>, args: any[], priority?: TaskPriority, signal?: AbortSignal, onProgress?: (progress: any) => void): Promise<T>;
	private getFreeWorker;
	private processQueue;
	private handleWorkerMessage;
	private handleWorkerError;
	private handleWorkerExit;
	private replaceWorker;
	private cleanupTask;
	cancelTask(id: string, reason?: string): boolean;
	shutdown(): void;
}
declare abstract class Event$1<K extends keyof BotEvents> {
	constructor({ name, pattern, patternOptions, once }: EventArguments<K>);
	execute(...args: Parameters<BotEvents[K]>): Promise<void> | void;
	getName(): string;
	getPattern(): RegExp | undefined;
	getPatternOptions(): chatPatternOptions;
	getRawName(): string;
	isOnce(): boolean;
}
export interface IModuleManifest {
	name: string;
	description: string;
	version: string;
	main: string;
	"api-version"?: string;
	author?: string | string[];
	website?: string;
	load?: "STARTUP" | "LOGIN" | "SPAWN";
	dependencies?: string[];
	softDependencies?: string[];
	loadBefore?: string[];
	permissions?: string[];
	commands?: Record<string, {
		description?: string;
		aliases?: string[];
		permission?: string;
		"permission-message"?: string;
		usage?: string;
	}>;
}
interface Bot$1 extends Bot {
	loadEvents: (dir: string) => void;
	pathfinder: unknown;
}
export type CommandExecute = (bot: Bot$1, sender: CommandSender, args: string[]) => void | Promise<void>;
export interface CommandInterface {
	name: string;
	execute: CommandExecute;
}
export interface EventInterface {
	name: string;
	once?: boolean;
	pattern?: RegExp;
	execute: (...args: unknown[]) => unknown;
}
export type Events = {
	botCreate: () => void;
	botSpawn: (bot: Bot$1) => void;
	clientReady: () => void;
};
export interface CommandBuilder {
	register: () => Response$1;
	toJson: () => CommandInterface;
	toString: () => string;
}
export interface EventArguments<K extends keyof BotEvents> {
	name: K;
	pattern?: RegExp;
	patternOptions?: chatPatternOptions;
	once?: boolean;
}
export type SettingsItem = {
	kind: "string";
	keyPath: string;
	label: string;
} | {
	kind: "number";
	keyPath: string;
	label: string;
} | {
	kind: "boolean";
	keyPath: string;
	label: string;
} | {
	kind: "select";
	keyPath: string;
	label: string;
	options: string[];
};
export type SettingsCategory = {
	id: string;
	title: string;
	items: SettingsItem[];
};
export interface SettingsApi {
	getConfig: () => unknown;
	set: (keyPath: string, value: unknown) => void;
	registerCategory: (category: SettingsCategory) => void;
	unregisterCategory: (id: string) => void;
}
declare global {
	namespace Xady {
		type Module = XadyModule;
		const Module: typeof XadyModule;
		type BaseModule = XadyModule;
		const BaseModule: typeof XadyModule;
		type Event<K extends keyof BotEvents = any> = Event$1<K>;
		const Event: typeof Event$1;
		type Command = any; /* Circular reference fixed */
		const Command: any; /* Circular reference fixed */
		type ConsoleCommandSender = any; /* Circular reference fixed */
		const ConsoleCommandSender: any; /* Circular reference fixed */
		type CommandSender = any; /* Circular reference fixed */
		const CommandSender: any; /* Circular reference fixed */
		type XadyEvent = any; /* Circular reference fixed */
		const XadyEvent: any; /* Circular reference fixed */
		type EventPriority = any; /* Circular reference fixed */
		const EventPriority: any; /* Circular reference fixed */
		const EventHandler: any; /* Circular reference fixed */
		type ServicePriority = any; /* Circular reference fixed */
		const ServicePriority: any; /* Circular reference fixed */
		type PluginCommand = any; /* Circular reference fixed */
		const PluginCommand: any; /* Circular reference fixed */
		type ModuleCommand = PluginCommand;
		const ModuleCommand: typeof PluginCommand;
		type WorkerPool = any; /* Circular reference fixed */
		const WorkerPool: any; /* Circular reference fixed */
		type TaskPriority = any; /* Circular reference fixed */
		const TaskPriority: any; /* Circular reference fixed */
		type FileConfiguration = any; /* Circular reference fixed */
		const FileConfiguration: any; /* Circular reference fixed */
		namespace events {
			type ConsoleCommandEvent = MineflayerEvents.ConsoleCommandEvent;
			const ConsoleCommandEvent: typeof MineflayerEvents.ConsoleCommandEvent;
			type ConsoleChatEvent = MineflayerEvents.ConsoleChatEvent;
			const ConsoleChatEvent: typeof MineflayerEvents.ConsoleChatEvent;
			type ChatPatternEvent = MineflayerEvents.ChatPatternEvent;
			const ChatPatternEvent: typeof MineflayerEvents.ChatPatternEvent;
			type GenericMineflayerEvent = MineflayerEvents.GenericMineflayerEvent;
			const GenericMineflayerEvent: typeof MineflayerEvents.GenericMineflayerEvent;
			type PlayerChatEvent = MineflayerEvents.PlayerChatEvent;
			const PlayerChatEvent: typeof MineflayerEvents.PlayerChatEvent;
			type MessageEvent = MineflayerEvents.MessageEvent;
			const MessageEvent: typeof MineflayerEvents.MessageEvent;
			type PlayerJoinEvent = MineflayerEvents.PlayerJoinEvent;
			const PlayerJoinEvent: typeof MineflayerEvents.PlayerJoinEvent;
			type PlayerLeftEvent = MineflayerEvents.PlayerLeftEvent;
			const PlayerLeftEvent: typeof MineflayerEvents.PlayerLeftEvent;
			type SpawnEvent = MineflayerEvents.SpawnEvent;
			const SpawnEvent: typeof MineflayerEvents.SpawnEvent;
			type DeathEvent = MineflayerEvents.DeathEvent;
			const DeathEvent: typeof MineflayerEvents.DeathEvent;
			type HealthEvent = MineflayerEvents.HealthEvent;
			const HealthEvent: typeof MineflayerEvents.HealthEvent;
			type KickedEvent = MineflayerEvents.KickedEvent;
			const KickedEvent: typeof MineflayerEvents.KickedEvent;
			type EndEvent = MineflayerEvents.EndEvent;
			const EndEvent: typeof MineflayerEvents.EndEvent;
			type ErrorEvent = MineflayerEvents.ErrorEvent;
			const ErrorEvent: typeof MineflayerEvents.ErrorEvent;
			type WhisperEvent = MineflayerEvents.WhisperEvent;
			const WhisperEvent: typeof MineflayerEvents.WhisperEvent;
			type EntitySpawnEvent = MineflayerEvents.EntitySpawnEvent;
			const EntitySpawnEvent: typeof MineflayerEvents.EntitySpawnEvent;
			type EntityGoneEvent = MineflayerEvents.EntityGoneEvent;
			const EntityGoneEvent: typeof MineflayerEvents.EntityGoneEvent;
			type ActionBarEvent = MineflayerEvents.ActionBarEvent;
			const ActionBarEvent: typeof MineflayerEvents.ActionBarEvent;
			type MessageStrEvent = MineflayerEvents.MessageStrEvent;
			const MessageStrEvent: typeof MineflayerEvents.MessageStrEvent;
			type UnmatchedMessageEvent = MineflayerEvents.UnmatchedMessageEvent;
			const UnmatchedMessageEvent: typeof MineflayerEvents.UnmatchedMessageEvent;
			type InjectAllowedEvent = MineflayerEvents.InjectAllowedEvent;
			const InjectAllowedEvent: typeof MineflayerEvents.InjectAllowedEvent;
			type LoginEvent = MineflayerEvents.LoginEvent;
			const LoginEvent: typeof MineflayerEvents.LoginEvent;
			type RespawnEvent = MineflayerEvents.RespawnEvent;
			const RespawnEvent: typeof MineflayerEvents.RespawnEvent;
			type GameEvent = MineflayerEvents.GameEvent;
			const GameEvent: typeof MineflayerEvents.GameEvent;
			type TitleEvent = MineflayerEvents.TitleEvent;
			const TitleEvent: typeof MineflayerEvents.TitleEvent;
			type RainEvent = MineflayerEvents.RainEvent;
			const RainEvent: typeof MineflayerEvents.RainEvent;
			type TimeEvent = MineflayerEvents.TimeEvent;
			const TimeEvent: typeof MineflayerEvents.TimeEvent;
			type SpawnResetEvent = MineflayerEvents.SpawnResetEvent;
			const SpawnResetEvent: typeof MineflayerEvents.SpawnResetEvent;
			type BreathEvent = MineflayerEvents.BreathEvent;
			const BreathEvent: typeof MineflayerEvents.BreathEvent;
			type MoveEvent = MineflayerEvents.MoveEvent;
			const MoveEvent: typeof MineflayerEvents.MoveEvent;
			type ForcedMoveEvent = MineflayerEvents.ForcedMoveEvent;
			const ForcedMoveEvent: typeof MineflayerEvents.ForcedMoveEvent;
			type MountEvent = MineflayerEvents.MountEvent;
			const MountEvent: typeof MineflayerEvents.MountEvent;
			type DismountEvent = MineflayerEvents.DismountEvent;
			const DismountEvent: typeof MineflayerEvents.DismountEvent;
			type SleepEvent = MineflayerEvents.SleepEvent;
			const SleepEvent: typeof MineflayerEvents.SleepEvent;
			type WakeEvent = MineflayerEvents.WakeEvent;
			const WakeEvent: typeof MineflayerEvents.WakeEvent;
			type ExperienceEvent = MineflayerEvents.ExperienceEvent;
			const ExperienceEvent: typeof MineflayerEvents.ExperienceEvent;
			type UsedFireworkEvent = MineflayerEvents.UsedFireworkEvent;
			const UsedFireworkEvent: typeof MineflayerEvents.UsedFireworkEvent;
			type EntitySwingArmEvent = MineflayerEvents.EntitySwingArmEvent;
			const EntitySwingArmEvent: typeof MineflayerEvents.EntitySwingArmEvent;
			type EntityHurtEvent = MineflayerEvents.EntityHurtEvent;
			const EntityHurtEvent: typeof MineflayerEvents.EntityHurtEvent;
			type EntityDeadEvent = MineflayerEvents.EntityDeadEvent;
			const EntityDeadEvent: typeof MineflayerEvents.EntityDeadEvent;
			type EntityTamingEvent = MineflayerEvents.EntityTamingEvent;
			const EntityTamingEvent: typeof MineflayerEvents.EntityTamingEvent;
			type EntityTamedEvent = MineflayerEvents.EntityTamedEvent;
			const EntityTamedEvent: typeof MineflayerEvents.EntityTamedEvent;
			type EntityShakingOffWaterEvent = MineflayerEvents.EntityShakingOffWaterEvent;
			const EntityShakingOffWaterEvent: typeof MineflayerEvents.EntityShakingOffWaterEvent;
			type EntityEatingGrassEvent = MineflayerEvents.EntityEatingGrassEvent;
			const EntityEatingGrassEvent: typeof MineflayerEvents.EntityEatingGrassEvent;
			type EntityHandSwapEvent = MineflayerEvents.EntityHandSwapEvent;
			const EntityHandSwapEvent: typeof MineflayerEvents.EntityHandSwapEvent;
			type EntityWakeEvent = MineflayerEvents.EntityWakeEvent;
			const EntityWakeEvent: typeof MineflayerEvents.EntityWakeEvent;
			type EntityEatEvent = MineflayerEvents.EntityEatEvent;
			const EntityEatEvent: typeof MineflayerEvents.EntityEatEvent;
			type EntityCriticalEffectEvent = MineflayerEvents.EntityCriticalEffectEvent;
			const EntityCriticalEffectEvent: typeof MineflayerEvents.EntityCriticalEffectEvent;
			type EntityMagicCriticalEffectEvent = MineflayerEvents.EntityMagicCriticalEffectEvent;
			const EntityMagicCriticalEffectEvent: typeof MineflayerEvents.EntityMagicCriticalEffectEvent;
			type EntityCrouchEvent = MineflayerEvents.EntityCrouchEvent;
			const EntityCrouchEvent: typeof MineflayerEvents.EntityCrouchEvent;
			type EntityUncrouchEvent = MineflayerEvents.EntityUncrouchEvent;
			const EntityUncrouchEvent: typeof MineflayerEvents.EntityUncrouchEvent;
			type EntityEquipEvent = MineflayerEvents.EntityEquipEvent;
			const EntityEquipEvent: typeof MineflayerEvents.EntityEquipEvent;
			type EntitySleepEvent = MineflayerEvents.EntitySleepEvent;
			const EntitySleepEvent: typeof MineflayerEvents.EntitySleepEvent;
			type EntityElytraFlewEvent = MineflayerEvents.EntityElytraFlewEvent;
			const EntityElytraFlewEvent: typeof MineflayerEvents.EntityElytraFlewEvent;
			type ItemDropEvent = MineflayerEvents.ItemDropEvent;
			const ItemDropEvent: typeof MineflayerEvents.ItemDropEvent;
			type PlayerCollectEvent = MineflayerEvents.PlayerCollectEvent;
			const PlayerCollectEvent: typeof MineflayerEvents.PlayerCollectEvent;
			type EntityAttributesEvent = MineflayerEvents.EntityAttributesEvent;
			const EntityAttributesEvent: typeof MineflayerEvents.EntityAttributesEvent;
			type EntityMovedEvent = MineflayerEvents.EntityMovedEvent;
			const EntityMovedEvent: typeof MineflayerEvents.EntityMovedEvent;
			type EntityDetachEvent = MineflayerEvents.EntityDetachEvent;
			const EntityDetachEvent: typeof MineflayerEvents.EntityDetachEvent;
			type EntityAttachEvent = MineflayerEvents.EntityAttachEvent;
			const EntityAttachEvent: typeof MineflayerEvents.EntityAttachEvent;
			type EntityUpdateEvent = MineflayerEvents.EntityUpdateEvent;
			const EntityUpdateEvent: typeof MineflayerEvents.EntityUpdateEvent;
			type EntityEffectEvent = MineflayerEvents.EntityEffectEvent;
			const EntityEffectEvent: typeof MineflayerEvents.EntityEffectEvent;
			type EntityEffectEndEvent = MineflayerEvents.EntityEffectEndEvent;
			const EntityEffectEndEvent: typeof MineflayerEvents.EntityEffectEndEvent;
			type PlayerUpdatedEvent = MineflayerEvents.PlayerUpdatedEvent;
			const PlayerUpdatedEvent: typeof MineflayerEvents.PlayerUpdatedEvent;
			type BlockUpdateEvent = MineflayerEvents.BlockUpdateEvent;
			const BlockUpdateEvent: typeof MineflayerEvents.BlockUpdateEvent;
			type ChunkColumnLoadEvent = MineflayerEvents.ChunkColumnLoadEvent;
			const ChunkColumnLoadEvent: typeof MineflayerEvents.ChunkColumnLoadEvent;
			type ChunkColumnUnloadEvent = MineflayerEvents.ChunkColumnUnloadEvent;
			const ChunkColumnUnloadEvent: typeof MineflayerEvents.ChunkColumnUnloadEvent;
			type SoundEffectHeardEvent = MineflayerEvents.SoundEffectHeardEvent;
			const SoundEffectHeardEvent: typeof MineflayerEvents.SoundEffectHeardEvent;
			type HardcodedSoundEffectHeardEvent = MineflayerEvents.HardcodedSoundEffectHeardEvent;
			const HardcodedSoundEffectHeardEvent: typeof MineflayerEvents.HardcodedSoundEffectHeardEvent;
			type NoteHeardEvent = MineflayerEvents.NoteHeardEvent;
			const NoteHeardEvent: typeof MineflayerEvents.NoteHeardEvent;
			type PistonMoveEvent = MineflayerEvents.PistonMoveEvent;
			const PistonMoveEvent: typeof MineflayerEvents.PistonMoveEvent;
			type ChestLidMoveEvent = MineflayerEvents.ChestLidMoveEvent;
			const ChestLidMoveEvent: typeof MineflayerEvents.ChestLidMoveEvent;
			type BlockBreakProgressObservedEvent = MineflayerEvents.BlockBreakProgressObservedEvent;
			const BlockBreakProgressObservedEvent: typeof MineflayerEvents.BlockBreakProgressObservedEvent;
			type BlockBreakProgressEndEvent = MineflayerEvents.BlockBreakProgressEndEvent;
			const BlockBreakProgressEndEvent: typeof MineflayerEvents.BlockBreakProgressEndEvent;
			type DiggingCompletedEvent = MineflayerEvents.DiggingCompletedEvent;
			const DiggingCompletedEvent: typeof MineflayerEvents.DiggingCompletedEvent;
			type DiggingAbortedEvent = MineflayerEvents.DiggingAbortedEvent;
			const DiggingAbortedEvent: typeof MineflayerEvents.DiggingAbortedEvent;
			type WindowOpenEvent = MineflayerEvents.WindowOpenEvent;
			const WindowOpenEvent: typeof MineflayerEvents.WindowOpenEvent;
			type WindowCloseEvent = MineflayerEvents.WindowCloseEvent;
			const WindowCloseEvent: typeof MineflayerEvents.WindowCloseEvent;
			type PhysicsTickEvent = MineflayerEvents.PhysicsTickEvent;
			const PhysicsTickEvent: typeof MineflayerEvents.PhysicsTickEvent;
			type ScoreboardCreatedEvent = MineflayerEvents.ScoreboardCreatedEvent;
			const ScoreboardCreatedEvent: typeof MineflayerEvents.ScoreboardCreatedEvent;
			type ScoreboardDeletedEvent = MineflayerEvents.ScoreboardDeletedEvent;
			const ScoreboardDeletedEvent: typeof MineflayerEvents.ScoreboardDeletedEvent;
			type ScoreboardTitleChangedEvent = MineflayerEvents.ScoreboardTitleChangedEvent;
			const ScoreboardTitleChangedEvent: typeof MineflayerEvents.ScoreboardTitleChangedEvent;
			type ScoreUpdatedEvent = MineflayerEvents.ScoreUpdatedEvent;
			const ScoreUpdatedEvent: typeof MineflayerEvents.ScoreUpdatedEvent;
			type ScoreRemovedEvent = MineflayerEvents.ScoreRemovedEvent;
			const ScoreRemovedEvent: typeof MineflayerEvents.ScoreRemovedEvent;
			type ScoreboardPositionEvent = MineflayerEvents.ScoreboardPositionEvent;
			const ScoreboardPositionEvent: typeof MineflayerEvents.ScoreboardPositionEvent;
			type TeamCreatedEvent = MineflayerEvents.TeamCreatedEvent;
			const TeamCreatedEvent: typeof MineflayerEvents.TeamCreatedEvent;
			type TeamRemovedEvent = MineflayerEvents.TeamRemovedEvent;
			const TeamRemovedEvent: typeof MineflayerEvents.TeamRemovedEvent;
			type TeamUpdatedEvent = MineflayerEvents.TeamUpdatedEvent;
			const TeamUpdatedEvent: typeof MineflayerEvents.TeamUpdatedEvent;
			type TeamMemberAddedEvent = MineflayerEvents.TeamMemberAddedEvent;
			const TeamMemberAddedEvent: typeof MineflayerEvents.TeamMemberAddedEvent;
			type TeamMemberRemovedEvent = MineflayerEvents.TeamMemberRemovedEvent;
			const TeamMemberRemovedEvent: typeof MineflayerEvents.TeamMemberRemovedEvent;
			type BossBarCreatedEvent = MineflayerEvents.BossBarCreatedEvent;
			const BossBarCreatedEvent: typeof MineflayerEvents.BossBarCreatedEvent;
			type BossBarDeletedEvent = MineflayerEvents.BossBarDeletedEvent;
			const BossBarDeletedEvent: typeof MineflayerEvents.BossBarDeletedEvent;
			type BossBarUpdatedEvent = MineflayerEvents.BossBarUpdatedEvent;
			const BossBarUpdatedEvent: typeof MineflayerEvents.BossBarUpdatedEvent;
			type ResourcePackEvent = MineflayerEvents.ResourcePackEvent;
			const ResourcePackEvent: typeof MineflayerEvents.ResourcePackEvent;
			type ParticleEvent = MineflayerEvents.ParticleEvent;
			const ParticleEvent: typeof MineflayerEvents.ParticleEvent;
		}
		type Listener = any; /* Circular reference fixed */
		const settings: SettingsApi;
		const prefix: {
			xady: typeof xady;
			error: typeof error;
			event: typeof event;
			success: typeof success;
			command: typeof command;
			module: typeof module$1;
		};
	}
}

declare namespace MineflayerEvents {
	export { ActionBarEvent, BlockBreakProgressEndEvent, BlockBreakProgressObservedEvent, BlockUpdateEvent, BossBarCreatedEvent, BossBarDeletedEvent, BossBarUpdatedEvent, BreathEvent, ChatPatternEvent, ChestLidMoveEvent, ChunkColumnLoadEvent, ChunkColumnUnloadEvent, ClientChatTypeEvent, ConsoleChatEvent, ConsoleCommandEvent, DeathEvent, DiggingAbortedEvent, DiggingCompletedEvent, DismountEvent, EndEvent, EntityAttachEvent, EntityAttributesEvent, EntityCriticalEffectEvent, EntityCrouchEvent, EntityDeadEvent, EntityDetachEvent, EntityEatEvent, EntityEatingGrassEvent, EntityEffectEndEvent, EntityEffectEvent, EntityElytraFlewEvent, EntityEquipEvent, EntityGoneEvent, EntityHandSwapEvent, EntityHurtEvent, EntityMagicCriticalEffectEvent, EntityMovedEvent, EntityShakingOffWaterEvent, EntitySleepEvent, EntitySpawnEvent, EntitySwingArmEvent, EntityTamedEvent, EntityTamingEvent, EntityUncrouchEvent, EntityUpdateEvent, EntityWakeEvent, ErrorEvent$1 as ErrorEvent, ExperienceEvent, ForcedMoveEvent, GameEvent, GenericMineflayerEvent, HardcodedSoundEffectHeardEvent, HealthEvent, InjectAllowedEvent, ItemDropEvent, KickedEvent, LoginEvent, MessageEvent$1 as MessageEvent, MessageStrEvent, MountEvent, MoveEvent, NoteHeardEvent, ParticleEvent, PhysicsTickEvent, PistonMoveEvent, PlayerChatEvent, PlayerCollectEvent, PlayerJoinEvent, PlayerLeftEvent, PlayerUpdatedEvent, RainEvent, ResourcePackEvent, RespawnEvent, ScoreRemovedEvent, ScoreUpdatedEvent, ScoreboardCreatedEvent, ScoreboardDeletedEvent, ScoreboardPositionEvent, ScoreboardTitleChangedEvent, SleepEvent, SoundEffectHeardEvent, SpawnEvent, SpawnResetEvent, TeamCreatedEvent, TeamMemberAddedEvent, TeamMemberRemovedEvent, TeamRemovedEvent, TeamUpdatedEvent, TimeEvent, TitleEvent, UnmatchedMessageEvent, UsedFireworkEvent, WakeEvent, WhisperEvent, WindowCloseEvent, WindowOpenEvent };
}

export {
	Bot$1 as Bot,
	Event$1 as Event,
	MineflayerEvents,
	PluginCommand as ModuleCommand,
	Response$1 as Response,
	XadyModule as BaseModule,
	module$1 as module,
};

export {};
