import { Listener } from "../../../event/Listener";
import { BlockUpdateEvent } from "../../../event/mineflayer/BlockUpdateEvent";
import { BossBarCreatedEvent } from "../../../event/mineflayer/BossBarCreatedEvent";
import { ChunkColumnLoadEvent } from "../../../event/mineflayer/ChunkColumnLoadEvent";
import { DeathEvent } from "../../../event/mineflayer/DeathEvent";
import { DismountEvent } from "../../../event/mineflayer/DismountEvent";
import { EndEvent } from "../../../event/mineflayer/EndEvent";
import { EntityGoneEvent } from "../../../event/mineflayer/EntityGoneEvent";
import { EntityHurtEvent } from "../../../event/mineflayer/EntityHurtEvent";
import { EntitySpawnEvent } from "../../../event/mineflayer/EntitySpawnEvent";
import { ExperienceEvent } from "../../../event/mineflayer/ExperienceEvent";
import { GenericMineflayerEvent } from "../../../event/mineflayer/GenericMineflayerEvent";
import { HealthEvent } from "../../../event/mineflayer/HealthEvent";
import { KickedEvent } from "../../../event/mineflayer/KickedEvent";
import { LoginEvent } from "../../../event/mineflayer/LoginEvent";
import { MessageStrEvent } from "../../../event/mineflayer/MessageStrEvent";
import { MountEvent } from "../../../event/mineflayer/MountEvent";
import { MoveEvent } from "../../../event/mineflayer/MoveEvent";
import { PlayerChatEvent } from "../../../event/mineflayer/PlayerChatEvent";
import { PlayerJoinEvent } from "../../../event/mineflayer/PlayerJoinEvent";
import { PlayerLeftEvent } from "../../../event/mineflayer/PlayerLeftEvent";
import { RainEvent } from "../../../event/mineflayer/RainEvent";
import { ScoreboardCreatedEvent } from "../../../event/mineflayer/ScoreboardCreatedEvent";
import { ScoreUpdatedEvent } from "../../../event/mineflayer/ScoreUpdatedEvent";
import { SoundEffectHeardEvent } from "../../../event/mineflayer/SoundEffectHeardEvent";
import { SpawnEvent } from "../../../event/mineflayer/SpawnEvent";
import { TeamCreatedEvent } from "../../../event/mineflayer/TeamCreatedEvent";
import { TimeEvent } from "../../../event/mineflayer/TimeEvent";
import { WhisperEvent } from "../../../event/mineflayer/WhisperEvent";
import { WindowCloseEvent } from "../../../event/mineflayer/WindowCloseEvent";
import { WindowOpenEvent } from "../../../event/mineflayer/WindowOpenEvent";
export default class AllEventsListener implements Listener {
    onSpawn(event: SpawnEvent): Promise<void>;
    onLogin(event: LoginEvent): Promise<void>;
    onPlayerJoin(event: PlayerJoinEvent): Promise<void>;
    onPlayerLeft(event: PlayerLeftEvent): Promise<void>;
    onChat(event: PlayerChatEvent): Promise<void>;
    onWhisper(event: WhisperEvent): Promise<void>;
    onMessage(event: MessageStrEvent): Promise<void>;
    onHealth(event: HealthEvent): Promise<void>;
    onDeath(event: DeathEvent): Promise<void>;
    onEntitySpawn(event: EntitySpawnEvent): Promise<void>;
    onEntityGone(event: EntityGoneEvent): Promise<void>;
    onEntityHurt(event: EntityHurtEvent): Promise<void>;
    onBlockUpdate(event: BlockUpdateEvent): Promise<void>;
    onChunkLoad(event: ChunkColumnLoadEvent): Promise<void>;
    onSound(event: SoundEffectHeardEvent): Promise<void>;
    onWindowOpen(event: WindowOpenEvent): Promise<void>;
    onWindowClose(event: WindowCloseEvent): Promise<void>;
    onScoreboardCreated(event: ScoreboardCreatedEvent): Promise<void>;
    onScoreUpdated(event: ScoreUpdatedEvent): Promise<void>;
    onTeamCreated(event: TeamCreatedEvent): Promise<void>;
    onBossBarCreated(event: BossBarCreatedEvent): Promise<void>;
    onRain(event: RainEvent): Promise<void>;
    onTime(event: TimeEvent): Promise<void>;
    onMove(event: MoveEvent): Promise<void>;
    onMount(event: MountEvent): Promise<void>;
    onDismount(event: DismountEvent): Promise<void>;
    onExperience(event: ExperienceEvent): Promise<void>;
    onError(event: Error): Promise<void>;
    onKicked(event: KickedEvent): Promise<void>;
    onEnd(event: EndEvent): Promise<void>;
    onGeneric(event: GenericMineflayerEvent): Promise<void>;
    private getClient;
}
